import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
    name: '『推荐友链』',
    desc: '',
    entries: [{
        author: '',
        sitenick: '',
        title: '清羽飞扬',
        desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
        link: 'https://blog.liushen.fun/',
        feed: 'https://blog.liushen.fun/atom.xml',
        icon: '',
        avatar: 'https://blog.liushen.fun/info/avatar.ico',
        archs: ['hexo', 'butterfly', 'service'],
        date: '2025-03-15',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '轻笑Chuckle',
        desc: '漫天倾尘风中轻笑',
        link: 'https://www.qcqx.cn',
        feed: '',
        icon: '',
        avatar: 'https://www.qcqx.cn/head.webp',
        archs: ['hexo', 'butterfly', 'vercel'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '贰猹的小窝',
        desc: '用这生命中的每一秒，给自己一个不后悔的未来',
        link: 'https://noionion.top/',
        feed: '',
        icon: '',
        avatar: 'https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg',
        archs: ['hexo', 'butterfly'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '安知鱼',
        desc: '生活明朗，万物可爱',
        link: 'https://blog.anheyu.com/',
        feed: '',
        icon: '',
        avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
        archs: ['hexo', 'butterfly'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '随风起',
        desc: '爱意随风起，风止意难平',
        link: 'https://blog.bywind.xyz/',
        feed: '',
        icon: '',
        avatar: 'https://blog.bywind.xyz/img/avatar.png',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '王先森',
        desc: '运维与安全从业者！',
        link: 'https://www.boysec.cn',
        feed: '',
        icon: '',
        avatar: 'https://images.boysec.cn/medias/avatar.jpg',
        archs: [],
        date: '',
        comment: '',
    }],
}, {
    name: '『2025』',
    desc: '在2025年添加友链的朋友们',
    entries: [{
        author: '',
        sitenick: '',
        title: '安小歪',
        desc: '记住你！自己！',
        link: 'https://blog.anxy.top/',
        feed: '',
        icon: '',
        avatar: 'https://imgse.koxiuqiu.cc/imgse/u/19/2025/02/20/67b737d854192.webp',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: 'Leonus',
        desc: '进一寸有进一寸的欢喜。',
        link: 'https://blog.leonus.cn/',
        feed: 'https://blog.leonus.cn/atom.xml',
        icon: '',
        avatar: 'https://q1.qlogo.cn/g?b=qq&nk=990320751&s=5',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: 'Ariasakaの小窝',
        desc: '人有悲欢离合 月有阴晴圆缺',
        link: 'https://blog.yaria.top',
        feed: '',
        icon: '',
        avatar: 'https://bu.dusays.com/2024/12/05/67517bcf104da.png',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '别亦难',
        desc: '准时不定期更新',
        link: 'https://lazyingman.cn',
        feed: '',
        icon: '',
        avatar: 'https://bu.dusays.com/2023/06/23/64959cf745a4d.png',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '小吉崽汁の窝',
        desc: 'A programmer of vegetable chicken',
        link: 'https://wuxingzzz.top',
        feed: '',
        icon: '',
        avatar: 'https://www.wuxingzzz.top/hexo/1716691173759791105.jpg',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '前尘小筑',
        desc: '虽多尘色染，犹见墨痕浓',
        link: 'https://mnchen.cn/',
        feed: '',
        icon: '',
        avatar: 'https://image.mnchen.cn/2023/12/mnochen.jpg',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '唐志远',
        desc: '古今之成大事者，不惟有超世之才，亦必有坚忍不拔之志',
        link: 'https://fe32.top/',
        feed: '',
        icon: '',
        avatar: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '葱苓小筑',
        desc: 'Don’t worry, be happy',
        link: 'https://blog.ciraos.top',
        feed: '',
        icon: '',
        avatar: 'https://blog.ciraos.top/avatar.avif',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '❖星港◎Star☆',
        desc: '以博客记录生活与热爱！',
        link: 'https://blog.starsharbor.com',
        feed: '',
        icon: '',
        avatar: 'https://bu.dusays.com/2025/04/11/67f92f6fcfb26.webp',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '呓语梦轩',
        desc: '用心享受生活',
        link: 'https://blog.awaae001.top',
        feed: 'https://blog.awaae001.top/atom.xml',
        icon: '',
        avatar: 'https://image.m-c.top/?/images/2024/01/13/Pqeh0v6VaK/ico.jpg',
        archs: [],
        date: '',
        comment: '',
    }],
}] satisfies FeedGroup[]
