import type { FeedGroup } from '~/types/feed'
import { getGhAvatar } from './utils/img'

export default [{
    name: '『推荐友链』',
    desc: '',
    entries: [{
        author: '',
        sitenick: '',
        title: '清羽飞扬',
        desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
        link: 'https://blog.liushen.fun/',
        feed: 'https://blog.liushen.fun/atom.xml',
        icon: '',
        avatar: 'https://blog.liushen.fun/info/avatar.ico',
        archs: ['hexo', 'butterfly', 'service'],
        date: '2025-03-15',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '轻笑Chuckle',
        desc: '漫天倾尘风中轻笑',
        link: 'https://www.qcqx.cn',
        feed: '',
        icon: '',
        avatar: 'https://www.qcqx.cn/head.webp',
        archs: ['hexo', 'butterfly', 'vercel'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '贰猹的小窝',
        desc: '用这生命中的每一秒，给自己一个不后悔的未来',
        link: 'https://noionion.top/',
        feed: '',
        icon: '',
        avatar: 'https://pub-noionion.oss-cn-hangzhou.aliyuncs.com/head.jpg',
        archs: ['hexo', 'butterfly'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '安知鱼',
        desc: '生活明朗，万物可爱',
        link: 'https://blog.anheyu.com/',
        feed: '',
        icon: '',
        avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
        archs: ['hexo', 'butterfly'],
        date: '2025-03-19',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '随风起',
        desc: '爱意随风起，风止意难平',
        link: 'https://blog.bywind.xyz/',
        feed: '',
        icon: '',
        avatar: 'https://blog.bywind.xyz/img/avatar.png',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '王先森',
        desc: '运维与安全从业者！',
        link: 'https://www.boysec.cn',
        feed: '',
        icon: '',
        avatar: 'https://images.boysec.cn/medias/avatar.jpg',
        archs: [],
        date: '',
        comment: '',
    }],
}, {
    name: '『2025』',
    desc: '西安邮电大学的校友们。',
    entries: [{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    },{
        author: '',
        sitenick: '',
        title: '',
        desc: '',
        link: '',
        feed: '',
        icon: '',
        avatar: '',
        archs: [],
        date: '',
        comment: '',
    }],
}] satisfies FeedGroup[]
